print('Please enter some text:')
x = input()
print('Text entered:',x)
print('Type:', type(x))
print('Great job Ash, now convert some strings to integers for later use!')
print('Please enter a single-digit integer value into this string')
y = input()
print('Please enter an double-digit integer value into this string')
z = input()
num1 = int(y)
num2 = int(z)
print(num1, '+', num2, '=', num1 + num2)